# Testing the Http Calls


GET http://localhost:4004/user/Tasks
###


GET https://b9ada367trial-dev-project-tracker-srv.cfapps.us10-001.hana.ondemand.com/getTasks(user='Marcus')

####

POST http://localhost:4004/admin/Tasks
Content-Type: application/json

{"TaskName": "Allocate Budgets", "AssignedDate": "2023-07-15", "AssignedTo": "Nikhitha", "AssignedBy": "Lisa", "CompleteBy": "2023-08-15", "Status": "Completed"}