# Testing the Http Calls


GET http://localhost:4004/user/Tasks
###


GET https://b9ada367trial-dev-project-tracker-srv.cfapps.us10-001.hana.ondemand.com/getTasks(user='Marcus')

####

POST https://b9ada367trial-dev-project-tracker-srv.cfapps.us10-001.hana.ondemand.com/admin/Tasks
Content-Type: application/json

{"TaskName": "Document the requirements", "AssignedDate": "2023-07-04", "AssignedTo": "Ryan", "AssignedBy": "Lisa", "CompleteBy": "2023-08-01", "Status": "Completed"}